// Autogenerated from Pigeon (v4.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif


/// Generated class from Pigeon.

///Generated class from Pigeon that represents data sent in messages.
struct DartInitParams {
  var sdkId: String
  var sdkToken: String
  var appName: String
  var serverAddress: String
  var serverDomain: String
  var envName: String
  var envId: String
  var envDomain: String
  var envDebugMode: Bool
  var preferLanguage: String

  static func fromMap(_ map: [String: Any?]) -> DartInitParams? {
    let sdkId = map["sdkId"] as! String
    let sdkToken = map["sdkToken"] as! String
    let appName = map["appName"] as! String
    let serverAddress = map["serverAddress"] as! String
    let serverDomain = map["serverDomain"] as! String
    let envName = map["envName"] as! String
    let envId = map["envId"] as! String
    let envDomain = map["envDomain"] as! String
    let envDebugMode = map["envDebugMode"] as! Bool
    let preferLanguage = map["preferLanguage"] as! String

    return DartInitParams(
      sdkId: sdkId,
      sdkToken: sdkToken,
      appName: appName,
      serverAddress: serverAddress,
      serverDomain: serverDomain,
      envName: envName,
      envId: envId,
      envDomain: envDomain,
      envDebugMode: envDebugMode,
      preferLanguage: preferLanguage
    )
  }
  func toMap() -> [String: Any?] {
    return [
      "sdkId": sdkId,
      "sdkToken": sdkToken,
      "appName": appName,
      "serverAddress": serverAddress,
      "serverDomain": serverDomain,
      "envName": envName,
      "envId": envId,
      "envDomain": envDomain,
      "envDebugMode": envDebugMode,
      "preferLanguage": preferLanguage
    ]
  }
}

///Generated class from Pigeon that represents data sent in messages.
struct DartTMJoinParam {
  /// 会议号
  var meetingCode: String
  /// 用户名
  var userDisplayName: String
  /// 会议密码
  var password: String
  /// 邀请链接
  var inviteUrl: String
  /// 是否开启麦克风
  var micOn: Bool
  /// 是否开启摄像头
  var cameraOn: Bool
  /// 是否开启扬声器
  var speakerOn: Bool
  var faceBeautyOn: Bool

  static func fromMap(_ map: [String: Any?]) -> DartTMJoinParam? {
    let meetingCode = map["meetingCode"] as! String
    let userDisplayName = map["userDisplayName"] as! String
    let password = map["password"] as! String
    let inviteUrl = map["inviteUrl"] as! String
    let micOn = map["micOn"] as! Bool
    let cameraOn = map["cameraOn"] as! Bool
    let speakerOn = map["speakerOn"] as! Bool
    let faceBeautyOn = map["faceBeautyOn"] as! Bool

    return DartTMJoinParam(
      meetingCode: meetingCode,
      userDisplayName: userDisplayName,
      password: password,
      inviteUrl: inviteUrl,
      micOn: micOn,
      cameraOn: cameraOn,
      speakerOn: speakerOn,
      faceBeautyOn: faceBeautyOn
    )
  }
  func toMap() -> [String: Any?] {
    return [
      "meetingCode": meetingCode,
      "userDisplayName": userDisplayName,
      "password": password,
      "inviteUrl": inviteUrl,
      "micOn": micOn,
      "cameraOn": cameraOn,
      "speakerOn": speakerOn,
      "faceBeautyOn": faceBeautyOn
    ]
  }
}
private class WeMeetApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return DartInitParams.fromMap(self.readValue() as! [String: Any])      
      case 129:
        return DartTMJoinParam.fromMap(self.readValue() as! [String: Any])      
      default:
        return super.readValue(ofType: type)
      
    }
  }
}
private class WeMeetApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DartInitParams {
      super.writeByte(128)
      super.writeValue(value.toMap())
    } else if let value = value as? DartTMJoinParam {
      super.writeByte(129)
      super.writeValue(value.toMap())
    } else {
      super.writeValue(value)
    }
  }
}

private class WeMeetApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WeMeetApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WeMeetApiCodecWriter(data: data)
  }
}

class WeMeetApiCodec: FlutterStandardMessageCodec {
  static let shared = WeMeetApiCodec(readerWriter: WeMeetApiCodecReaderWriter())
}

///Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WeMeetApi {
  func initWeMeet(param: DartInitParams)
  func loginWeMeet(ssoUrl: String)
  func joinMeeting(joinParam: DartTMJoinParam)
  func leaveMeeting()
  func releaseWeMeet()
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WeMeetApiSetup {
  /// The codec used by WeMeetApi.
  static var codec: FlutterStandardMessageCodec { WeMeetApiCodec.shared }
  /// Sets up an instance of `WeMeetApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WeMeetApi?) {
    let initWeMeetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.WeMeetApi.initWeMeet", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initWeMeetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramArg = args[0] as! DartInitParams
        api.initWeMeet(param: paramArg)
        reply(nil)
      }
    } else {
      initWeMeetChannel.setMessageHandler(nil)
    }
    let loginWeMeetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.WeMeetApi.loginWeMeet", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginWeMeetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ssoUrlArg = args[0] as! String
        api.loginWeMeet(ssoUrl: ssoUrlArg)
        reply(nil)
      }
    } else {
      loginWeMeetChannel.setMessageHandler(nil)
    }
    let joinMeetingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.WeMeetApi.joinMeeting", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinMeetingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let joinParamArg = args[0] as! DartTMJoinParam
        api.joinMeeting(joinParam: joinParamArg)
        reply(nil)
      }
    } else {
      joinMeetingChannel.setMessageHandler(nil)
    }
    let leaveMeetingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.WeMeetApi.leaveMeeting", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      leaveMeetingChannel.setMessageHandler { _, reply in
        api.leaveMeeting()
        reply(nil)
      }
    } else {
      leaveMeetingChannel.setMessageHandler(nil)
    }
    let releaseWeMeetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.WeMeetApi.releaseWeMeet", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseWeMeetChannel.setMessageHandler { _, reply in
        api.releaseWeMeet()
        reply(nil)
      }
    } else {
      releaseWeMeetChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [String: Any?] {
  return ["result": result]
}

private func wrapError(_ error: FlutterError) -> [String: Any?] {
  return [
    "error": [
      "code": error.code,
      "message": error.message,
      "details": error.details
    ]
  ]
}
