name: tencent_wemeet
description: A new Flutter project.
version: 3.12.4
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  pigeon:
    git:
      url: https://github.com/vickyleu/pigeon.git

flutter:
  plugin:
    platforms:
      android:
        package: com.example.tencent_wemeet
        pluginClass: TencentWemeetPlugin
      ios:
        pluginClass: TencentWemeetPlugin
      macos:
        pluginClass: TencentWemeetPlugin
      windows:
        pluginClass: TencentWemeetPluginCApi
