// Autogenerated from Pigeon (v4.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.flutter.plugins

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

/** Generated class from Pigeon. */

/** 错误码 */
enum class DartTMErrorCode(val raw: Int) {
  SUCCESS(0),
  SERVERCONFIGFAIL(1),
  INVALIDAUTHCODE(2),
  LOGOUTINMEETING(3),
  UNKNOWN(4),
  USERNOTAUTHORIZED(5),
  USERINMEETING(6),
  INVALIDPARAM(7),
  INVALIDMEETINGCODE(8),
  INVALIDNICKNAME(9),
  DUPLICATEINITCALL(10),
  ACCOUNTALREADYLOGIN(11),
  SDKNOTINITIALIZED(12),
  SYNCCALLTIMEOUT(13),
  NOTINMEETING(14),
  CANCELJOIN(15),
  ISLOGINING(16),
  LOGINNETERROR(17),
  TOKENVERIFYFAILED(18),
  CHILDPROCESSCRASH(19),
  MULTIACCOUNTLOGINCONFLICT(20),
  JOINMEETINGSERVICEFAILED(21),
  INVALIDJSONSTRING(22),
  PROXYSETFAILED(23);

  companion object {
    fun ofRaw(raw: Int): DartTMErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DartInitParams (
  val sdkId: String,
  val sdkToken: String,
  val appName: String,
  val serverAddress: String,
  val serverDomain: String,
  val envName: String,
  val envId: String,
  val envDomain: String,
  val envDebugMode: Boolean,
  val preferLanguage: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromMap(map: Map<String, Any?>): DartInitParams {
      val sdkId = map["sdkId"] as String
      val sdkToken = map["sdkToken"] as String
      val appName = map["appName"] as String
      val serverAddress = map["serverAddress"] as String
      val serverDomain = map["serverDomain"] as String
      val envName = map["envName"] as String
      val envId = map["envId"] as String
      val envDomain = map["envDomain"] as String
      val envDebugMode = map["envDebugMode"] as Boolean
      val preferLanguage = map["preferLanguage"] as String

      return DartInitParams(sdkId, sdkToken, appName, serverAddress, serverDomain, envName, envId, envDomain, envDebugMode, preferLanguage)
    }
  }
  fun toMap(): Map<String, Any?> {
    val map = mutableMapOf<String, Any?>()
    map["sdkId"] = sdkId
    map["sdkToken"] = sdkToken
    map["appName"] = appName
    map["serverAddress"] = serverAddress
    map["serverDomain"] = serverDomain
    map["envName"] = envName
    map["envId"] = envId
    map["envDomain"] = envDomain
    map["envDebugMode"] = envDebugMode
    map["preferLanguage"] = preferLanguage
    return map
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DartTMJoinParam (
  /** 会议号 */
  val meetingCode: String,
  /** 用户名 */
  val userDisplayName: String,
  /** 会议密码 */
  val password: String,
  /** 邀请链接 */
  val inviteUrl: String,
  /** 是否开启麦克风 */
  val micOn: Boolean,
  /** 是否开启摄像头 */
  val cameraOn: Boolean,
  /** 是否开启扬声器 */
  val speakerOn: Boolean,
  val faceBeautyOn: Boolean,
  val value: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromMap(map: Map<String, Any?>): DartTMJoinParam {
      val meetingCode = map["meetingCode"] as String
      val userDisplayName = map["userDisplayName"] as String
      val password = map["password"] as String
      val inviteUrl = map["inviteUrl"] as String
      val micOn = map["micOn"] as Boolean
      val cameraOn = map["cameraOn"] as Boolean
      val speakerOn = map["speakerOn"] as Boolean
      val faceBeautyOn = map["faceBeautyOn"] as Boolean
      val value = map["value"] as Long

      return DartTMJoinParam(meetingCode, userDisplayName, password, inviteUrl, micOn, cameraOn, speakerOn, faceBeautyOn, value)
    }
  }
  fun toMap(): Map<String, Any?> {
    val map = mutableMapOf<String, Any?>()
    map["meetingCode"] = meetingCode
    map["userDisplayName"] = userDisplayName
    map["password"] = password
    map["inviteUrl"] = inviteUrl
    map["micOn"] = micOn
    map["cameraOn"] = cameraOn
    map["speakerOn"] = speakerOn
    map["faceBeautyOn"] = faceBeautyOn
    map["value"] = value
    return map
  }
}
@Suppress("UNCHECKED_CAST")
private object WeMeetApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? Map<String, Any?>)?.let {
          DartInitParams.fromMap(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? Map<String, Any?>)?.let {
          DartTMJoinParam.fromMap(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DartInitParams -> {
        stream.write(128)
        writeValue(stream, value.toMap())
      }
      is DartTMJoinParam -> {
        stream.write(129)
        writeValue(stream, value.toMap())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WeMeetApi {
  /**
   * 初始化SDK并设置回调代理，通过SDKCallback.onSDKInitializeResult回调来返回初始化结果。
   * 初始化成功后，重复调用无效。
   * 除getSDKVersion之外，在调用的所有接口函数之前，必须第一个先调用该函数。
   * 按照个保法要求，App需要在用户同意了隐私协议之后才可以调用该初始化函数。
   */
  fun initWeMeet(param: DartInitParams)
  /** 判断是否已初始化SDK成功 */
  fun isInitialized(): Boolean
  /** 发起登录请求，登录结果会在回调AuthenticationCallback.onLogin返回。 */
  fun loginWeMeet(ssoUrl: String)
  /** 判断是否已登录 */
  fun isLoggedIn(): Boolean
  /**
   * 发起入会请求，结果会在回调PreMeetingCallback.onJoinMeeting返回。登录完成后，才可调用。
   * 如果想使用JoinParam参数中缺省的默认值，请使用joinMeetingByJSON函数
   */
  fun joinMeeting(joinParam: DartTMJoinParam)
  /** 发起离会请求，结果会在回调InMeetingCallback.onLeaveMeeting返回 */
  fun leaveMeeting()
  fun releaseWeMeet()
  /** 发起登出请求，登出结果会在回调AuthenticationCallback.onLogout返回。 */
  fun logout()
  /** 更新SDK Token，替换掉过期或快过期的SDK Token。 */
  fun refreshSDKToken(newSdkToken: String): Long

  companion object {
    /** The codec used by WeMeetApi. */
    val codec: MessageCodec<Any?> by lazy {
      WeMeetApiCodec
    }
    /** Sets up an instance of `WeMeetApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: WeMeetApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.initWeMeet", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              val args = message as List<Any?>
              val paramArg = args[0] as DartInitParams
              api.initWeMeet(paramArg)
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.isInitialized", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              wrapped["result"] = api.isInitialized()
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.loginWeMeet", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              val args = message as List<Any?>
              val ssoUrlArg = args[0] as String
              api.loginWeMeet(ssoUrlArg)
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.isLoggedIn", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              wrapped["result"] = api.isLoggedIn()
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.joinMeeting", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              val args = message as List<Any?>
              val joinParamArg = args[0] as DartTMJoinParam
              api.joinMeeting(joinParamArg)
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.leaveMeeting", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              api.leaveMeeting()
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.releaseWeMeet", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              api.releaseWeMeet()
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.logout", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              api.logout()
              wrapped["result"] = null
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.WeMeetApi.refreshSDKToken", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              val args = message as List<Any?>
              val newSdkTokenArg = args[0] as String
              wrapped["result"] = api.refreshSDKToken(newSdkTokenArg)
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private fun wrapResult(result: Any?): Map<String, Any?> {
  return hashMapOf("result" to result)
}

private fun wrapError(exception: Throwable): Map<String, Any> {
  return hashMapOf<String, Any>(
    "error" to hashMapOf<String, Any>(
      "code" to exception.javaClass.simpleName,
      "message" to exception.toString(),
      "details" to "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  )
}
